name: Node.js CI & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Build and Test (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x, 22.x, 23.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Set CHROME_PATH environment variable
        run: echo "CHROME_PATH=$(which google-chrome || which chromium || which chromium-browser || echo '/usr/bin/google-chrome')" >> $GITHUB_ENV

      - name: Run tests
        run: npm test